apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
spec:  # 相当于命令行后面的--，额外参数
  replicas: 3  # 副本数
  selector:  # 选择器
    matchLabels:
      run: nginx
  template:  # pod模板, 下面都是定义pod的一些参数
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.17.1
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP